x-otel-common:
  &otel-common
  OTEL_LOG_LEVEL: warning # The library does not respect this environment variable as of this writing
  OTEL_TRACES_SAMPLER: parentbased_always_on
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
  OTEL_PHP_TRACES_PROCESSOR: simple

version: '3.8'
services:
  
  # services Samples-Otel-PHP
  service-one:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:8.1
    command: [ 'php', '-S', '0.0.0.0:8000' ]
    volumes:
      - './src:/usr/src/myapp'
    ports:
      - '8000:8000'
    environment:
      <<: *otel-common
      OTEL_SERVICE_NAME: service-one
      OTEL_RESOURCE_ATTRIBUTES: 'service.version=0.1'
      
  service-two:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:8.1
    command: [ 'php', '-S', '0.0.0.0:8000' ]
    volumes:
      - './src:/usr/src/myapp'
    environment:
      <<: *otel-common
      OTEL_SERVICE_NAME: service-two
      OTEL_RESOURCE_ATTRIBUTES: 'service.version=0.2'
    
  service-three:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:8.1
    command: [ 'php', '-S', '0.0.0.0:8000' ]
    volumes:
      - './src:/usr/src/myapp'
    environment:
      <<: *otel-common
      OTEL_SERVICE_NAME: service-three
  
 # Jaeger (Otel Trace Data Browser)
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  # services Samples-Otel-DotNet-Core
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - '16379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

 # Collector
  collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector-gateway.yaml:/etc/collector-gateway.yaml
    command: [ "--config=/etc/collector-gateway.yaml" ]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
      #- "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
volumes:
  cache:
    driver: local
  db:
    driver: local